---
version: "3.7"

services:

  zanzito-thingsboard-exporter:
    image: techblog/zanzito-thingsboard-exporter
    container_name: zanzito-thingsboard-exporter
    restart: always
    environment:
      - TB_SERVER_ADDRESS= #eg. http://localhost:8080 http://my-server.addrsss https://mytb.com
      - REPORT_INTERVAL= #In minutes
      - MQTT_BROKER_ADDRESS=
      - MQTT_BROKER_PORT=1883
      - MQTT_BROKER_USER=
      - MQTT_BROKER_PASSWORD=
    volumes:
      - ./tasmota-tb/config:/app/config
